name: Sync to Gitee

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_PRIVATE_KEY }}
        with:
          source-repo: "git@github.com:clover-eric/cm-file-cabinet.git"
          destination-repo: "git@gitee.com:your-gitee-username/cm-file-cabinet.git" 